name: RRPersistence
options:
  bundleIdPrefix: com.rrpersistence
  deploymentTarget:
    iOS: "15.0"
    macOS: "12.0"
    tvOS: "15.0"
    watchOS: "8.0"
    visionOS: "1.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true
  generateSchemes: true

settings:
  SWIFT_VERSION: "5.9"
  ENABLE_TESTING_SEARCH_PATHS: true
  CLANG_ENABLE_MODULES: true
  SWIFT_INSTALL_OBJC_HEADER: false
  BUILD_LIBRARY_FOR_DISTRIBUTION: true
  SWIFT_COMPILATION_MODE: "wholemodule"
  OTHER_SWIFT_FLAGS: "-Xfrontend -warn-long-function-bodies=100 -Xfrontend -warn-long-expression-type-checking=100"

packages:
  RRFoundation:
    url: https://github.com/rirp53021/rr-swift-foundation.git
    from: 1.9.0
    generateScheme: false

targets:
  RRPersistence:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/RRPersistence
        excludes:
          - "**/*.plist"
    dependencies:
      - package: RRFoundation
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.rrpersistence.rrpersistence
      PRODUCT_NAME: RRPersistence
      CLANG_ENABLE_MODULES: "YES"
      SWIFT_INSTALL_OBJC_HEADER: "NO"
      BUILD_LIBRARY_FOR_DISTRIBUTION: "YES"
      SWIFT_ENABLE_LIBRARY_EVOLUTION: "YES"
      SWIFT_COMPILATION_MODE: "wholemodule"
      SKIP_INSTALL: "NO"
      DEFINES_MODULE: "YES"
      MACH_O_TYPE: mh_dylib
    info:
      path: Sources/RRPersistence/Info.plist
      properties:
        CFBundleName: RRPersistence
        CFBundleDisplayName: RRPersistence
        CFBundleIdentifier: com.rrpersistence.rrpersistence
        CFBundleVersion: "1.1.0"
        CFBundleShortVersionString: "1.1.0"
        CFBundlePackageType: FMWK
        CFBundleInfoDictionaryVersion: "6.0"

  RRPersistenceTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/RRPersistenceTests
    dependencies:
      - target: RRPersistence
    settings:
      PRODUCT_NAME: RRPersistenceTests
      PRODUCT_BUNDLE_IDENTIFIER: com.rrpersistence.tests
