name: RRPersistence
options:
  bundleIdPrefix: com.rrpersistence
  deploymentTarget:
    iOS: "15.0"
    macOS: "12.0"
    tvOS: "15.0"
    watchOS: "8.0"
    visionOS: "1.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true
  generateSchemes: true

settings:
  SWIFT_VERSION: "5.9"
  ENABLE_TESTING_SEARCH_PATHS: true
  CLANG_ENABLE_MODULES: true
  SWIFT_INSTALL_OBJC_HEADER: false
  BUILD_LIBRARY_FOR_DISTRIBUTION: true
  SWIFT_COMPILATION_MODE: "wholemodule"
  OTHER_SWIFT_FLAGS: "-Xfrontend -warn-long-function-bodies=100 -Xfrontend -warn-long-expression-type-checking=100"

packages:
  RRFoundation:
    url: https://github.com/rirp53021/rr-swift-foundation.git
    from: 1.8.0
    generateScheme: false

targets:
  RRPersistence:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/RRPersistence
    dependencies:
      - package: RRFoundation
    settings:
      PRODUCT_NAME: RRPersistence
      PRODUCT_BUNDLE_IDENTIFIER: com.rrpersistence.core
      CLANG_ENABLE_MODULES: true
      SWIFT_INSTALL_OBJC_HEADER: false
      BUILD_LIBRARY_FOR_DISTRIBUTION: true
      SWIFT_ENABLE_LIBRARY_EVOLUTION: true
      SWIFT_COMPILATION_MODE: "wholemodule"
      SKIP_INSTALL: false
      DEFINES_MODULE: false
    info:
      path: Sources/RRPersistence/Info.plist
      properties:
        CFBundleName: RRPersistence
        CFBundleDisplayName: RRPersistence
        CFBundleIdentifier: com.rrpersistence.core
        CFBundleVersion: "1.0.0"
        CFBundleShortVersionString: "1.0.2"
        CFBundlePackageType: FMWK
        CFBundleInfoDictionaryVersion: "6.0"

  RRPersistenceTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/RRPersistenceTests
    dependencies:
      - target: RRPersistence
    settings:
      PRODUCT_NAME: RRPersistenceTests
      PRODUCT_BUNDLE_IDENTIFIER: com.rrpersistence.tests
      ENABLE_TESTING_SEARCH_PATHS: true
      CODE_SIGNING_ALLOWED: false
      CODE_SIGNING_REQUIRED: false
    info:
      path: Tests/RRPersistenceTests/Info.plist
      properties:
        CFBundleName: RRPersistenceTests
        CFBundleDisplayName: RRPersistenceTests
        CFBundleIdentifier: com.rrpersistence.tests
        CFBundleVersion: "1.0.0"
        CFBundleShortVersionString: "1.0.2"
        CFBundlePackageType: BNDL
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: RRPersistenceTests
        CFBundleResourceSpecification: InfoPlist.strings
        NSHumanReadableCopyright: "Copyright (c) 2024 Ronald Ruiz. All rights reserved."
        LSRequiresIPhoneOS: true
        MinimumOSVersion: "15.0"

schemes:
  RRPersistence:
    build:
      targets:
        RRPersistence: all
    test:
      targets:
        - RRPersistenceTests
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

